"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# RUTA BASE: punto de referencia para construir paths de base de datos, estáticos y otros recursos.
BASE_DIR = Path(__file__).resolve().parent.parent


# ENTORNO DE DESARROLLO: estos valores son útiles localmente y deben endurecerse en producción.

# SEGURIDAD: clave interna usada por Django para sesiones, firmas y otras operaciones sensibles.
SECRET_KEY = 'django-insecure-qq3cv*fy_a9(3%!_5_ri6og$!ut8ce3kf8b2$=ia86y_8#8j+a'

# MODO DEBUG: habilita trazas y utilidades de desarrollo.
DEBUG = True

# HOSTS PERMITIDOS: lista vacía porque el proyecto está preparado para correr localmente.
ALLOWED_HOSTS = []


# APPS INSTALADAS: módulos base de Django y la app principal donde vive el CRUD de snippets.

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'vault',
]

# MIDDLEWARE: cadena de procesamiento para seguridad, sesión, autenticación y mensajes.
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ENRUTAMIENTO RAÍZ: archivo que delega las URLs generales del proyecto.
ROOT_URLCONF = 'config.urls'

# TEMPLATES: configuración del motor de plantillas y de los context processors globales.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# DESPLIEGUE WSGI: punto de entrada para servidores compatibles con WSGI.
WSGI_APPLICATION = 'config.wsgi.application'


# BASE DE DATOS: se usa SQLite para mantener el proyecto simple en desarrollo.

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# VALIDACIÓN DE CONTRASEÑAS: reglas estándar de Django para usuarios administrativos.

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# LOCALIZACIÓN: idioma y zona horaria por defecto para renderizado y fechas del sistema.

LANGUAGE_CODE = 'es-co'

TIME_ZONE = 'America/Bogota'

USE_I18N = True

USE_TZ = True


# ARCHIVOS ESTÁTICOS: prefijo desde el que Django expone CSS, JavaScript e imágenes.

STATIC_URL = 'static/'

# LLAVE PRIMARIA POR DEFECTO: tipo de ID automático para nuevos modelos.

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
