# Generated by Django 5.2.13 on 2026-04-08 01:28

from django.db import migrations, models


# MIGRACIÓN INICIAL: crea la tabla base del modelo Snippet con su estructura original.
class Migration(migrations.Migration):

    initial = True

    # DEPENDENCIAS: al ser la primera migración, no necesita pasos previos.
    dependencies = [
    ]

    # OPERACIONES: define la creación de la tabla y de cada campo persistido.
    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('lenguaje', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('sql', 'SQL'), ('django', 'Django'), ('git', 'Git')], max_length=20)),
                ('categoria', models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Base de datos'), ('devops', 'DevOps'), ('utils', 'Utilidades')], max_length=20)),
                ('descripcion', models.TextField()),
                ('codigo', models.TextField()),
                ('destacado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Snippet',
                'verbose_name_plural': 'Snippets',
                'ordering': ['-creado_en'],
            },
        ),
    ]
