# Generated by Django 5.2.13 on 2026-04-08 14:18

from django.db import migrations, models


# MIGRACIÓN DE AJUSTE: amplía la lista de lenguajes disponibles para el modelo Snippet.
class Migration(migrations.Migration):

    # DEPENDENCIA DIRECTA: este cambio se aplica después de la creación inicial del modelo.
    dependencies = [
        ('vault', '0001_initial'),
    ]

    # OPERACIÓN: actualiza el campo lenguaje para aceptar más opciones predefinidas.
    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lenguaje',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('sql', 'SQL'), ('django', 'Django'), ('git', 'Git'), ('docker', 'Docker'), ('regex', 'Regex'), ('json', 'JSON'), ('yaml', 'YAML')], max_length=20),
        ),
    ]
