# Generated by Django 5.2.13 on 2026-04-08 14:18
# esta migración se encarga de modificar el campo lenguaje del modelo Snippet para agregar nuevas opciones de lenguajes.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lenguaje',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript'), ('html', 'HTML'), ('css', 'CSS'), ('bash', 'Bash'), ('sql', 'SQL'), ('django', 'Django'), ('git', 'Git'), ('docker', 'Docker'), ('regex', 'Regex'), ('json', 'JSON'), ('yaml', 'YAML')], max_length=20),
        ),
    ]
